api:
  ~chart: app
  ~needs: [build-api]
  imagePackage: api
  containerPort: 3000
  probesPath: "/healthz"
  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000

jobs:
  runs:
    build-api:
      use: build
      with:
        imagePackage: api
        context: ./api
        buildArgs:
          COMMIT_SHA: "{{ $.Values.global.sha }}"
