name: 🚀 Production
on:
  workflow_dispatch:
  push:
    tags:
      - v*

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  build-api:
    name: Build API
    runs-on: ubuntu-latest
    steps:
      - name: Use autodevops build and register
        uses: socialgouv/workflows/actions/build-image@v1
        with:
          imagePackage: api
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: prod
          dockerfile: ./api/Dockerfile
          dockercontext: ./api
          dockerbuildargs: |
            PRODUCTION=true

  kontinuous:
    name: "Deploy on Kubernetes 🐳"
    needs: [build-api]
    uses: socialgouv/workflows/.github/workflows/use-ks-gh-production.yaml@v1
    secrets: inherit
